/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum TopologyStatus
{
  ACTIVE = 1,
  INACTIVE = 2,
  REBALANCING = 3,
  KILLED = 4,
}
