#if !NETSTANDARD13
/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;



public partial class ExecutorSpecificStats : TBase
{
  private BoltStats _bolt;
  private SpoutStats _spout;

  public BoltStats Bolt
  {
    get
    {
      return _bolt;
    }
    set
    {
      __isset.bolt = true;
      this._bolt = value;
    }
  }

  public SpoutStats Spout
  {
    get
    {
      return _spout;
    }
    set
    {
      __isset.spout = true;
      this._spout = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool bolt;
    public bool spout;
  }

  public ExecutorSpecificStats() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.Struct) {
            Bolt = new BoltStats();
            Bolt.Read(iprot);
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 2:
          if (field.Type == TType.Struct) {
            Spout = new SpoutStats();
            Spout.Read(iprot);
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("ExecutorSpecificStats");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (Bolt != null && __isset.bolt) {
      field.Name = "bolt";
      field.Type = TType.Struct;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      Bolt.Write(oprot);
      oprot.WriteFieldEnd();
    }
    if (Spout != null && __isset.spout) {
      field.Name = "spout";
      field.Type = TType.Struct;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      Spout.Write(oprot);
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("ExecutorSpecificStats(");
    bool __first = true;
    if (Bolt != null && __isset.bolt) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Bolt: ");
      __sb.Append(Bolt== null ? "<null>" : Bolt.ToString());
    }
    if (Spout != null && __isset.spout) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Spout: ");
      __sb.Append(Spout== null ? "<null>" : Spout.ToString());
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}
#endif