#if !NETSTANDARD13
/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;



public partial class LocalStateData : TBase
{

  public Dictionary<string, ThriftSerializedObject> Serialized_parts { get; set; }

  public LocalStateData() {
  }

  public LocalStateData(Dictionary<string, ThriftSerializedObject> serialized_parts) : this() {
    this.Serialized_parts = serialized_parts;
  }

  public void Read (TProtocol iprot)
  {
    bool isset_serialized_parts = false;
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.Map) {
            {
              Serialized_parts = new Dictionary<string, ThriftSerializedObject>();
              TMap _map218 = iprot.ReadMapBegin();
              for( int _i219 = 0; _i219 < _map218.Count; ++_i219)
              {
                string _key220;
                ThriftSerializedObject _val221;
                _key220 = iprot.ReadString();
                _val221 = new ThriftSerializedObject();
                _val221.Read(iprot);
                Serialized_parts[_key220] = _val221;
              }
              iprot.ReadMapEnd();
            }
            isset_serialized_parts = true;
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
    if (!isset_serialized_parts)
      throw new TProtocolException(TProtocolException.INVALID_DATA);
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("LocalStateData");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    field.Name = "serialized_parts";
    field.Type = TType.Map;
    field.ID = 1;
    oprot.WriteFieldBegin(field);
    {
      oprot.WriteMapBegin(new TMap(TType.String, TType.Struct, Serialized_parts.Count));
      foreach (string _iter222 in Serialized_parts.Keys)
      {
        oprot.WriteString(_iter222);
        Serialized_parts[_iter222].Write(oprot);
      }
      oprot.WriteMapEnd();
    }
    oprot.WriteFieldEnd();
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("LocalStateData(");
    __sb.Append(", Serialized_parts: ");
    __sb.Append(Serialized_parts);
    __sb.Append(")");
    return __sb.ToString();
  }

}
#endif