#if !NETSTANDARD13
/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;



public partial class LocalAssignment : TBase
{

  public string Topology_id { get; set; }

  public List<ExecutorInfo> Executors { get; set; }

  public LocalAssignment() {
  }

  public LocalAssignment(string topology_id, List<ExecutorInfo> executors) : this() {
    this.Topology_id = topology_id;
    this.Executors = executors;
  }

  public void Read (TProtocol iprot)
  {
    bool isset_topology_id = false;
    bool isset_executors = false;
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.String) {
            Topology_id = iprot.ReadString();
            isset_topology_id = true;
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 2:
          if (field.Type == TType.List) {
            {
              Executors = new List<ExecutorInfo>();
              TList _list223 = iprot.ReadListBegin();
              for( int _i224 = 0; _i224 < _list223.Count; ++_i224)
              {
                ExecutorInfo _elem225;
                _elem225 = new ExecutorInfo();
                _elem225.Read(iprot);
                Executors.Add(_elem225);
              }
              iprot.ReadListEnd();
            }
            isset_executors = true;
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
    if (!isset_topology_id)
      throw new TProtocolException(TProtocolException.INVALID_DATA);
    if (!isset_executors)
      throw new TProtocolException(TProtocolException.INVALID_DATA);
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("LocalAssignment");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    field.Name = "topology_id";
    field.Type = TType.String;
    field.ID = 1;
    oprot.WriteFieldBegin(field);
    oprot.WriteString(Topology_id);
    oprot.WriteFieldEnd();
    field.Name = "executors";
    field.Type = TType.List;
    field.ID = 2;
    oprot.WriteFieldBegin(field);
    {
      oprot.WriteListBegin(new TList(TType.Struct, Executors.Count));
      foreach (ExecutorInfo _iter226 in Executors)
      {
        _iter226.Write(oprot);
      }
      oprot.WriteListEnd();
    }
    oprot.WriteFieldEnd();
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("LocalAssignment(");
    __sb.Append(", Topology_id: ");
    __sb.Append(Topology_id);
    __sb.Append(", Executors: ");
    __sb.Append(Executors);
    __sb.Append(")");
    return __sb.ToString();
  }

}
#endif