/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class LSSupervisorAssignments : TBase
{

  public Dictionary<int, LocalAssignment> Assignments { get; set; }

  public LSSupervisorAssignments() {
  }

  public LSSupervisorAssignments(Dictionary<int, LocalAssignment> assignments) : this() {
    this.Assignments = assignments;
  }

  public void Read (TProtocol iprot)
  {
    bool isset_assignments = false;
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.Map) {
            {
              Assignments = new Dictionary<int, LocalAssignment>();
              TMap _map232 = iprot.ReadMapBegin();
              for( int _i233 = 0; _i233 < _map232.Count; ++_i233)
              {
                int _key234;
                LocalAssignment _val235;
                _key234 = iprot.ReadI32();
                _val235 = new LocalAssignment();
                _val235.Read(iprot);
                Assignments[_key234] = _val235;
              }
              iprot.ReadMapEnd();
            }
            isset_assignments = true;
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
    if (!isset_assignments)
      throw new TProtocolException(TProtocolException.INVALID_DATA);
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("LSSupervisorAssignments");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    field.Name = "assignments";
    field.Type = TType.Map;
    field.ID = 1;
    oprot.WriteFieldBegin(field);
    {
      oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, Assignments.Count));
      foreach (int _iter236 in Assignments.Keys)
      {
        oprot.WriteI32(_iter236);
        Assignments[_iter236].Write(oprot);
      }
      oprot.WriteMapEnd();
    }
    oprot.WriteFieldEnd();
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("LSSupervisorAssignments(");
    __sb.Append(", Assignments: ");
    __sb.Append(Assignments);
    __sb.Append(")");
    return __sb.ToString();
  }

}

