/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class RebalanceOptions : TBase
{
  private int _wait_secs;
  private int _num_workers;
  private Dictionary<string, int> _num_executors;

  public int Wait_secs
  {
    get
    {
      return _wait_secs;
    }
    set
    {
      __isset.wait_secs = true;
      this._wait_secs = value;
    }
  }

  public int Num_workers
  {
    get
    {
      return _num_workers;
    }
    set
    {
      __isset.num_workers = true;
      this._num_workers = value;
    }
  }

  public Dictionary<string, int> Num_executors
  {
    get
    {
      return _num_executors;
    }
    set
    {
      __isset.num_executors = true;
      this._num_executors = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool wait_secs;
    public bool num_workers;
    public bool num_executors;
  }

  public RebalanceOptions() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.I32) {
            Wait_secs = iprot.ReadI32();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 2:
          if (field.Type == TType.I32) {
            Num_workers = iprot.ReadI32();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 3:
          if (field.Type == TType.Map) {
            {
              Num_executors = new Dictionary<string, int>();
              TMap _map158 = iprot.ReadMapBegin();
              for( int _i159 = 0; _i159 < _map158.Count; ++_i159)
              {
                string _key160;
                int _val161;
                _key160 = iprot.ReadString();
                _val161 = iprot.ReadI32();
                Num_executors[_key160] = _val161;
              }
              iprot.ReadMapEnd();
            }
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("RebalanceOptions");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (__isset.wait_secs) {
      field.Name = "wait_secs";
      field.Type = TType.I32;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteI32(Wait_secs);
      oprot.WriteFieldEnd();
    }
    if (__isset.num_workers) {
      field.Name = "num_workers";
      field.Type = TType.I32;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteI32(Num_workers);
      oprot.WriteFieldEnd();
    }
    if (Num_executors != null && __isset.num_executors) {
      field.Name = "num_executors";
      field.Type = TType.Map;
      field.ID = 3;
      oprot.WriteFieldBegin(field);
      {
        oprot.WriteMapBegin(new TMap(TType.String, TType.I32, Num_executors.Count));
        foreach (string _iter162 in Num_executors.Keys)
        {
          oprot.WriteString(_iter162);
          oprot.WriteI32(Num_executors[_iter162]);
        }
        oprot.WriteMapEnd();
      }
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("RebalanceOptions(");
    bool __first = true;
    if (__isset.wait_secs) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Wait_secs: ");
      __sb.Append(Wait_secs);
    }
    if (__isset.num_workers) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Num_workers: ");
      __sb.Append(Num_workers);
    }
    if (Num_executors != null && __isset.num_executors) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Num_executors: ");
      __sb.Append(Num_executors);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

